package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CitaProducto generated by hbm2java
 */
public class CitaProducto  implements java.io.Serializable {


     private CitaProductoId id;
     private Cita cita;
     private BigDecimal citpCita;
     private String citpProducto;

    public CitaProducto() {
    }

	
    public CitaProducto(CitaProductoId id, Cita cita) {
        this.id = id;
        this.cita = cita;
    }
    public CitaProducto(CitaProductoId id, Cita cita, BigDecimal citpCita, String citpProducto) {
       this.id = id;
       this.cita = cita;
       this.citpCita = citpCita;
       this.citpProducto = citpProducto;
    }
   
    public CitaProductoId getId() {
        return this.id;
    }
    
    public void setId(CitaProductoId id) {
        this.id = id;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public BigDecimal getCitpCita() {
        return this.citpCita;
    }
    
    public void setCitpCita(BigDecimal citpCita) {
        this.citpCita = citpCita;
    }
    public String getCitpProducto() {
        return this.citpProducto;
    }
    
    public void setCitpProducto(String citpProducto) {
        this.citpProducto = citpProducto;
    }




}


