package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ClienteId generated by hbm2java
 */
public class ClienteId  implements java.io.Serializable {


     private BigDecimal cliCliente;
     private BigDecimal facturaFacFactura;
     private BigDecimal facturaCitaCita;

    public ClienteId() {
    }

    public ClienteId(BigDecimal cliCliente, BigDecimal facturaFacFactura, BigDecimal facturaCitaCita) {
       this.cliCliente = cliCliente;
       this.facturaFacFactura = facturaFacFactura;
       this.facturaCitaCita = facturaCitaCita;
    }
   
    public BigDecimal getCliCliente() {
        return this.cliCliente;
    }
    
    public void setCliCliente(BigDecimal cliCliente) {
        this.cliCliente = cliCliente;
    }
    public BigDecimal getFacturaFacFactura() {
        return this.facturaFacFactura;
    }
    
    public void setFacturaFacFactura(BigDecimal facturaFacFactura) {
        this.facturaFacFactura = facturaFacFactura;
    }
    public BigDecimal getFacturaCitaCita() {
        return this.facturaCitaCita;
    }
    
    public void setFacturaCitaCita(BigDecimal facturaCitaCita) {
        this.facturaCitaCita = facturaCitaCita;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClienteId) ) return false;
		 ClienteId castOther = ( ClienteId ) other; 
         
		 return ( (this.getCliCliente()==castOther.getCliCliente()) || ( this.getCliCliente()!=null && castOther.getCliCliente()!=null && this.getCliCliente().equals(castOther.getCliCliente()) ) )
 && ( (this.getFacturaFacFactura()==castOther.getFacturaFacFactura()) || ( this.getFacturaFacFactura()!=null && castOther.getFacturaFacFactura()!=null && this.getFacturaFacFactura().equals(castOther.getFacturaFacFactura()) ) )
 && ( (this.getFacturaCitaCita()==castOther.getFacturaCitaCita()) || ( this.getFacturaCitaCita()!=null && castOther.getFacturaCitaCita()!=null && this.getFacturaCitaCita().equals(castOther.getFacturaCitaCita()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCliCliente() == null ? 0 : this.getCliCliente().hashCode() );
         result = 37 * result + ( getFacturaFacFactura() == null ? 0 : this.getFacturaFacFactura().hashCode() );
         result = 37 * result + ( getFacturaCitaCita() == null ? 0 : this.getFacturaCitaCita().hashCode() );
         return result;
   }   


}


