package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CorteCaja generated by hbm2java
 */
public class CorteCaja  implements java.io.Serializable {


     private BigDecimal corCorcaja;
     private Date corFecha;
     private BigDecimal corSaldoini;
     private BigDecimal corIngresos;
     private BigDecimal corEgresos;
     private Set corteCajadetalles = new HashSet(0);

    public CorteCaja() {
    }

	
    public CorteCaja(BigDecimal corCorcaja) {
        this.corCorcaja = corCorcaja;
    }
    public CorteCaja(BigDecimal corCorcaja, Date corFecha, BigDecimal corSaldoini, BigDecimal corIngresos, BigDecimal corEgresos, Set corteCajadetalles) {
       this.corCorcaja = corCorcaja;
       this.corFecha = corFecha;
       this.corSaldoini = corSaldoini;
       this.corIngresos = corIngresos;
       this.corEgresos = corEgresos;
       this.corteCajadetalles = corteCajadetalles;
    }
   
    public BigDecimal getCorCorcaja() {
        return this.corCorcaja;
    }
    
    public void setCorCorcaja(BigDecimal corCorcaja) {
        this.corCorcaja = corCorcaja;
    }
    public Date getCorFecha() {
        return this.corFecha;
    }
    
    public void setCorFecha(Date corFecha) {
        this.corFecha = corFecha;
    }
    public BigDecimal getCorSaldoini() {
        return this.corSaldoini;
    }
    
    public void setCorSaldoini(BigDecimal corSaldoini) {
        this.corSaldoini = corSaldoini;
    }
    public BigDecimal getCorIngresos() {
        return this.corIngresos;
    }
    
    public void setCorIngresos(BigDecimal corIngresos) {
        this.corIngresos = corIngresos;
    }
    public BigDecimal getCorEgresos() {
        return this.corEgresos;
    }
    
    public void setCorEgresos(BigDecimal corEgresos) {
        this.corEgresos = corEgresos;
    }
    public Set getCorteCajadetalles() {
        return this.corteCajadetalles;
    }
    
    public void setCorteCajadetalles(Set corteCajadetalles) {
        this.corteCajadetalles = corteCajadetalles;
    }




}


