package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CorteCajadetalleId generated by hbm2java
 */
public class CorteCajadetalleId  implements java.io.Serializable {


     private BigDecimal cordCajade;
     private BigDecimal facturaFacFactura;
     private BigDecimal facturaCitaCita;
     private BigDecimal corteCajaCorCorcaja;

    public CorteCajadetalleId() {
    }

    public CorteCajadetalleId(BigDecimal cordCajade, BigDecimal facturaFacFactura, BigDecimal facturaCitaCita, BigDecimal corteCajaCorCorcaja) {
       this.cordCajade = cordCajade;
       this.facturaFacFactura = facturaFacFactura;
       this.facturaCitaCita = facturaCitaCita;
       this.corteCajaCorCorcaja = corteCajaCorCorcaja;
    }
   
    public BigDecimal getCordCajade() {
        return this.cordCajade;
    }
    
    public void setCordCajade(BigDecimal cordCajade) {
        this.cordCajade = cordCajade;
    }
    public BigDecimal getFacturaFacFactura() {
        return this.facturaFacFactura;
    }
    
    public void setFacturaFacFactura(BigDecimal facturaFacFactura) {
        this.facturaFacFactura = facturaFacFactura;
    }
    public BigDecimal getFacturaCitaCita() {
        return this.facturaCitaCita;
    }
    
    public void setFacturaCitaCita(BigDecimal facturaCitaCita) {
        this.facturaCitaCita = facturaCitaCita;
    }
    public BigDecimal getCorteCajaCorCorcaja() {
        return this.corteCajaCorCorcaja;
    }
    
    public void setCorteCajaCorCorcaja(BigDecimal corteCajaCorCorcaja) {
        this.corteCajaCorCorcaja = corteCajaCorCorcaja;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CorteCajadetalleId) ) return false;
		 CorteCajadetalleId castOther = ( CorteCajadetalleId ) other; 
         
		 return ( (this.getCordCajade()==castOther.getCordCajade()) || ( this.getCordCajade()!=null && castOther.getCordCajade()!=null && this.getCordCajade().equals(castOther.getCordCajade()) ) )
 && ( (this.getFacturaFacFactura()==castOther.getFacturaFacFactura()) || ( this.getFacturaFacFactura()!=null && castOther.getFacturaFacFactura()!=null && this.getFacturaFacFactura().equals(castOther.getFacturaFacFactura()) ) )
 && ( (this.getFacturaCitaCita()==castOther.getFacturaCitaCita()) || ( this.getFacturaCitaCita()!=null && castOther.getFacturaCitaCita()!=null && this.getFacturaCitaCita().equals(castOther.getFacturaCitaCita()) ) )
 && ( (this.getCorteCajaCorCorcaja()==castOther.getCorteCajaCorCorcaja()) || ( this.getCorteCajaCorCorcaja()!=null && castOther.getCorteCajaCorCorcaja()!=null && this.getCorteCajaCorCorcaja().equals(castOther.getCorteCajaCorCorcaja()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCordCajade() == null ? 0 : this.getCordCajade().hashCode() );
         result = 37 * result + ( getFacturaFacFactura() == null ? 0 : this.getFacturaFacFactura().hashCode() );
         result = 37 * result + ( getFacturaCitaCita() == null ? 0 : this.getFacturaCitaCita().hashCode() );
         result = 37 * result + ( getCorteCajaCorCorcaja() == null ? 0 : this.getCorteCajaCorCorcaja().hashCode() );
         return result;
   }   


}


