package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CorteCajadetalle generated by hbm2java
 */
public class CorteCajadetalle  implements java.io.Serializable {


     private CorteCajadetalleId id;
     private CorteCaja corteCaja;
     private Factura factura;
     private BigDecimal cordCortecaja;
     private BigDecimal cordFactura;

    public CorteCajadetalle() {
    }

	
    public CorteCajadetalle(CorteCajadetalleId id, CorteCaja corteCaja, Factura factura) {
        this.id = id;
        this.corteCaja = corteCaja;
        this.factura = factura;
    }
    public CorteCajadetalle(CorteCajadetalleId id, CorteCaja corteCaja, Factura factura, BigDecimal cordCortecaja, BigDecimal cordFactura) {
       this.id = id;
       this.corteCaja = corteCaja;
       this.factura = factura;
       this.cordCortecaja = cordCortecaja;
       this.cordFactura = cordFactura;
    }
   
    public CorteCajadetalleId getId() {
        return this.id;
    }
    
    public void setId(CorteCajadetalleId id) {
        this.id = id;
    }
    public CorteCaja getCorteCaja() {
        return this.corteCaja;
    }
    
    public void setCorteCaja(CorteCaja corteCaja) {
        this.corteCaja = corteCaja;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public BigDecimal getCordCortecaja() {
        return this.cordCortecaja;
    }
    
    public void setCordCortecaja(BigDecimal cordCortecaja) {
        this.cordCortecaja = cordCortecaja;
    }
    public BigDecimal getCordFactura() {
        return this.cordFactura;
    }
    
    public void setCordFactura(BigDecimal cordFactura) {
        this.cordFactura = cordFactura;
    }




}


