package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private BigDecimal depDepartamento;
     private String depNombre;
     private String depDescripcion;
     private Set puestos = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(BigDecimal depDepartamento) {
        this.depDepartamento = depDepartamento;
    }
    public Departamento(BigDecimal depDepartamento, String depNombre, String depDescripcion, Set puestos) {
       this.depDepartamento = depDepartamento;
       this.depNombre = depNombre;
       this.depDescripcion = depDescripcion;
       this.puestos = puestos;
    }
   
    public BigDecimal getDepDepartamento() {
        return this.depDepartamento;
    }
    
    public void setDepDepartamento(BigDecimal depDepartamento) {
        this.depDepartamento = depDepartamento;
    }
    public String getDepNombre() {
        return this.depNombre;
    }
    
    public void setDepNombre(String depNombre) {
        this.depNombre = depNombre;
    }
    public String getDepDescripcion() {
        return this.depDescripcion;
    }
    
    public void setDepDescripcion(String depDescripcion) {
        this.depDescripcion = depDescripcion;
    }
    public Set getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set puestos) {
        this.puestos = puestos;
    }




}


