package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private EmpleadoId id;
     private Empleado empleado;
     private Persona persona;
     private BigDecimal empPersona;
     private Date empFechaIngreso;
     private String empPuesto;
     private BigDecimal empSalario;
     private BigDecimal empJefe;
     private String empEstado;
     private BigDecimal puePuesto;
     private Set empleados = new HashSet(0);
     private Set nominaDetalles = new HashSet(0);
     private Set puestos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(EmpleadoId id, Empleado empleado, Persona persona) {
        this.id = id;
        this.empleado = empleado;
        this.persona = persona;
    }
    public Empleado(EmpleadoId id, Empleado empleado, Persona persona, BigDecimal empPersona, Date empFechaIngreso, String empPuesto, BigDecimal empSalario, BigDecimal empJefe, String empEstado, BigDecimal puePuesto, Set empleados, Set nominaDetalles, Set puestos) {
       this.id = id;
       this.empleado = empleado;
       this.persona = persona;
       this.empPersona = empPersona;
       this.empFechaIngreso = empFechaIngreso;
       this.empPuesto = empPuesto;
       this.empSalario = empSalario;
       this.empJefe = empJefe;
       this.empEstado = empEstado;
       this.puePuesto = puePuesto;
       this.empleados = empleados;
       this.nominaDetalles = nominaDetalles;
       this.puestos = puestos;
    }
   
    public EmpleadoId getId() {
        return this.id;
    }
    
    public void setId(EmpleadoId id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public BigDecimal getEmpPersona() {
        return this.empPersona;
    }
    
    public void setEmpPersona(BigDecimal empPersona) {
        this.empPersona = empPersona;
    }
    public Date getEmpFechaIngreso() {
        return this.empFechaIngreso;
    }
    
    public void setEmpFechaIngreso(Date empFechaIngreso) {
        this.empFechaIngreso = empFechaIngreso;
    }
    public String getEmpPuesto() {
        return this.empPuesto;
    }
    
    public void setEmpPuesto(String empPuesto) {
        this.empPuesto = empPuesto;
    }
    public BigDecimal getEmpSalario() {
        return this.empSalario;
    }
    
    public void setEmpSalario(BigDecimal empSalario) {
        this.empSalario = empSalario;
    }
    public BigDecimal getEmpJefe() {
        return this.empJefe;
    }
    
    public void setEmpJefe(BigDecimal empJefe) {
        this.empJefe = empJefe;
    }
    public String getEmpEstado() {
        return this.empEstado;
    }
    
    public void setEmpEstado(String empEstado) {
        this.empEstado = empEstado;
    }
    public BigDecimal getPuePuesto() {
        return this.puePuesto;
    }
    
    public void setPuePuesto(BigDecimal puePuesto) {
        this.puePuesto = puePuesto;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getNominaDetalles() {
        return this.nominaDetalles;
    }
    
    public void setNominaDetalles(Set nominaDetalles) {
        this.nominaDetalles = nominaDetalles;
    }
    public Set getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(Set puestos) {
        this.puestos = puestos;
    }




}


