package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EmpleadoId generated by hbm2java
 */
public class EmpleadoId  implements java.io.Serializable {


     private BigDecimal empEmpleado;
     private BigDecimal personaPerPersona;
     private BigDecimal personaPacientePacPaciente;

    public EmpleadoId() {
    }

    public EmpleadoId(BigDecimal empEmpleado, BigDecimal personaPerPersona, BigDecimal personaPacientePacPaciente) {
       this.empEmpleado = empEmpleado;
       this.personaPerPersona = personaPerPersona;
       this.personaPacientePacPaciente = personaPacientePacPaciente;
    }
   
    public BigDecimal getEmpEmpleado() {
        return this.empEmpleado;
    }
    
    public void setEmpEmpleado(BigDecimal empEmpleado) {
        this.empEmpleado = empEmpleado;
    }
    public BigDecimal getPersonaPerPersona() {
        return this.personaPerPersona;
    }
    
    public void setPersonaPerPersona(BigDecimal personaPerPersona) {
        this.personaPerPersona = personaPerPersona;
    }
    public BigDecimal getPersonaPacientePacPaciente() {
        return this.personaPacientePacPaciente;
    }
    
    public void setPersonaPacientePacPaciente(BigDecimal personaPacientePacPaciente) {
        this.personaPacientePacPaciente = personaPacientePacPaciente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoId) ) return false;
		 EmpleadoId castOther = ( EmpleadoId ) other; 
         
		 return ( (this.getEmpEmpleado()==castOther.getEmpEmpleado()) || ( this.getEmpEmpleado()!=null && castOther.getEmpEmpleado()!=null && this.getEmpEmpleado().equals(castOther.getEmpEmpleado()) ) )
 && ( (this.getPersonaPerPersona()==castOther.getPersonaPerPersona()) || ( this.getPersonaPerPersona()!=null && castOther.getPersonaPerPersona()!=null && this.getPersonaPerPersona().equals(castOther.getPersonaPerPersona()) ) )
 && ( (this.getPersonaPacientePacPaciente()==castOther.getPersonaPacientePacPaciente()) || ( this.getPersonaPacientePacPaciente()!=null && castOther.getPersonaPacientePacPaciente()!=null && this.getPersonaPacientePacPaciente().equals(castOther.getPersonaPacientePacPaciente()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmpEmpleado() == null ? 0 : this.getEmpEmpleado().hashCode() );
         result = 37 * result + ( getPersonaPerPersona() == null ? 0 : this.getPersonaPerPersona().hashCode() );
         result = 37 * result + ( getPersonaPacientePacPaciente() == null ? 0 : this.getPersonaPacientePacPaciente().hashCode() );
         return result;
   }   


}


