package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private FacturaId id;
     private Cita cita;
     private BigDecimal facNofactura;
     private BigDecimal facSerie;
     private Date facFecha;
     private String facCliente;
     private BigDecimal facCita;
     private String facEstado;
     private BigDecimal facTotal;
     private Set clientes = new HashSet(0);
     private Set facturaDetalles = new HashSet(0);
     private Set corteCajadetalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(FacturaId id, Cita cita) {
        this.id = id;
        this.cita = cita;
    }
    public Factura(FacturaId id, Cita cita, BigDecimal facNofactura, BigDecimal facSerie, Date facFecha, String facCliente, BigDecimal facCita, String facEstado, BigDecimal facTotal, Set clientes, Set facturaDetalles, Set corteCajadetalles) {
       this.id = id;
       this.cita = cita;
       this.facNofactura = facNofactura;
       this.facSerie = facSerie;
       this.facFecha = facFecha;
       this.facCliente = facCliente;
       this.facCita = facCita;
       this.facEstado = facEstado;
       this.facTotal = facTotal;
       this.clientes = clientes;
       this.facturaDetalles = facturaDetalles;
       this.corteCajadetalles = corteCajadetalles;
    }
   
    public FacturaId getId() {
        return this.id;
    }
    
    public void setId(FacturaId id) {
        this.id = id;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public BigDecimal getFacNofactura() {
        return this.facNofactura;
    }
    
    public void setFacNofactura(BigDecimal facNofactura) {
        this.facNofactura = facNofactura;
    }
    public BigDecimal getFacSerie() {
        return this.facSerie;
    }
    
    public void setFacSerie(BigDecimal facSerie) {
        this.facSerie = facSerie;
    }
    public Date getFacFecha() {
        return this.facFecha;
    }
    
    public void setFacFecha(Date facFecha) {
        this.facFecha = facFecha;
    }
    public String getFacCliente() {
        return this.facCliente;
    }
    
    public void setFacCliente(String facCliente) {
        this.facCliente = facCliente;
    }
    public BigDecimal getFacCita() {
        return this.facCita;
    }
    
    public void setFacCita(BigDecimal facCita) {
        this.facCita = facCita;
    }
    public String getFacEstado() {
        return this.facEstado;
    }
    
    public void setFacEstado(String facEstado) {
        this.facEstado = facEstado;
    }
    public BigDecimal getFacTotal() {
        return this.facTotal;
    }
    
    public void setFacTotal(BigDecimal facTotal) {
        this.facTotal = facTotal;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set getCorteCajadetalles() {
        return this.corteCajadetalles;
    }
    
    public void setCorteCajadetalles(Set corteCajadetalles) {
        this.corteCajadetalles = corteCajadetalles;
    }




}


