package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaDetalleId generated by hbm2java
 */
public class FacturaDetalleId  implements java.io.Serializable {


     private BigDecimal facdFacturade;
     private BigDecimal facturaFacFactura;
     private BigDecimal facturaCitaCita;
     private BigDecimal productoProProducto;

    public FacturaDetalleId() {
    }

    public FacturaDetalleId(BigDecimal facdFacturade, BigDecimal facturaFacFactura, BigDecimal facturaCitaCita, BigDecimal productoProProducto) {
       this.facdFacturade = facdFacturade;
       this.facturaFacFactura = facturaFacFactura;
       this.facturaCitaCita = facturaCitaCita;
       this.productoProProducto = productoProProducto;
    }
   
    public BigDecimal getFacdFacturade() {
        return this.facdFacturade;
    }
    
    public void setFacdFacturade(BigDecimal facdFacturade) {
        this.facdFacturade = facdFacturade;
    }
    public BigDecimal getFacturaFacFactura() {
        return this.facturaFacFactura;
    }
    
    public void setFacturaFacFactura(BigDecimal facturaFacFactura) {
        this.facturaFacFactura = facturaFacFactura;
    }
    public BigDecimal getFacturaCitaCita() {
        return this.facturaCitaCita;
    }
    
    public void setFacturaCitaCita(BigDecimal facturaCitaCita) {
        this.facturaCitaCita = facturaCitaCita;
    }
    public BigDecimal getProductoProProducto() {
        return this.productoProProducto;
    }
    
    public void setProductoProProducto(BigDecimal productoProProducto) {
        this.productoProProducto = productoProProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaDetalleId) ) return false;
		 FacturaDetalleId castOther = ( FacturaDetalleId ) other; 
         
		 return ( (this.getFacdFacturade()==castOther.getFacdFacturade()) || ( this.getFacdFacturade()!=null && castOther.getFacdFacturade()!=null && this.getFacdFacturade().equals(castOther.getFacdFacturade()) ) )
 && ( (this.getFacturaFacFactura()==castOther.getFacturaFacFactura()) || ( this.getFacturaFacFactura()!=null && castOther.getFacturaFacFactura()!=null && this.getFacturaFacFactura().equals(castOther.getFacturaFacFactura()) ) )
 && ( (this.getFacturaCitaCita()==castOther.getFacturaCitaCita()) || ( this.getFacturaCitaCita()!=null && castOther.getFacturaCitaCita()!=null && this.getFacturaCitaCita().equals(castOther.getFacturaCitaCita()) ) )
 && ( (this.getProductoProProducto()==castOther.getProductoProProducto()) || ( this.getProductoProProducto()!=null && castOther.getProductoProProducto()!=null && this.getProductoProProducto().equals(castOther.getProductoProProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFacdFacturade() == null ? 0 : this.getFacdFacturade().hashCode() );
         result = 37 * result + ( getFacturaFacFactura() == null ? 0 : this.getFacturaFacFactura().hashCode() );
         result = 37 * result + ( getFacturaCitaCita() == null ? 0 : this.getFacturaCitaCita().hashCode() );
         result = 37 * result + ( getProductoProProducto() == null ? 0 : this.getProductoProProducto().hashCode() );
         return result;
   }   


}


