package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaDetalle generated by hbm2java
 */
public class FacturaDetalle  implements java.io.Serializable {


     private FacturaDetalleId id;
     private Factura factura;
     private Producto producto;
     private BigDecimal facdFactura;
     private String facdProducto;
     private BigDecimal facdCantidad;
     private BigDecimal facdPreciouni;
     private BigDecimal facdDescuento;

    public FacturaDetalle() {
    }

	
    public FacturaDetalle(FacturaDetalleId id, Factura factura, Producto producto) {
        this.id = id;
        this.factura = factura;
        this.producto = producto;
    }
    public FacturaDetalle(FacturaDetalleId id, Factura factura, Producto producto, BigDecimal facdFactura, String facdProducto, BigDecimal facdCantidad, BigDecimal facdPreciouni, BigDecimal facdDescuento) {
       this.id = id;
       this.factura = factura;
       this.producto = producto;
       this.facdFactura = facdFactura;
       this.facdProducto = facdProducto;
       this.facdCantidad = facdCantidad;
       this.facdPreciouni = facdPreciouni;
       this.facdDescuento = facdDescuento;
    }
   
    public FacturaDetalleId getId() {
        return this.id;
    }
    
    public void setId(FacturaDetalleId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getFacdFactura() {
        return this.facdFactura;
    }
    
    public void setFacdFactura(BigDecimal facdFactura) {
        this.facdFactura = facdFactura;
    }
    public String getFacdProducto() {
        return this.facdProducto;
    }
    
    public void setFacdProducto(String facdProducto) {
        this.facdProducto = facdProducto;
    }
    public BigDecimal getFacdCantidad() {
        return this.facdCantidad;
    }
    
    public void setFacdCantidad(BigDecimal facdCantidad) {
        this.facdCantidad = facdCantidad;
    }
    public BigDecimal getFacdPreciouni() {
        return this.facdPreciouni;
    }
    
    public void setFacdPreciouni(BigDecimal facdPreciouni) {
        this.facdPreciouni = facdPreciouni;
    }
    public BigDecimal getFacdDescuento() {
        return this.facdDescuento;
    }
    
    public void setFacdDescuento(BigDecimal facdDescuento) {
        this.facdDescuento = facdDescuento;
    }




}


