package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaId generated by hbm2java
 */
public class FacturaId  implements java.io.Serializable {


     private BigDecimal facFactura;
     private BigDecimal citaCitaCita;

    public FacturaId() {
    }

    public FacturaId(BigDecimal facFactura, BigDecimal citaCitaCita) {
       this.facFactura = facFactura;
       this.citaCitaCita = citaCitaCita;
    }
   
    public BigDecimal getFacFactura() {
        return this.facFactura;
    }
    
    public void setFacFactura(BigDecimal facFactura) {
        this.facFactura = facFactura;
    }
    public BigDecimal getCitaCitaCita() {
        return this.citaCitaCita;
    }
    
    public void setCitaCitaCita(BigDecimal citaCitaCita) {
        this.citaCitaCita = citaCitaCita;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaId) ) return false;
		 FacturaId castOther = ( FacturaId ) other; 
         
		 return ( (this.getFacFactura()==castOther.getFacFactura()) || ( this.getFacFactura()!=null && castOther.getFacFactura()!=null && this.getFacFactura().equals(castOther.getFacFactura()) ) )
 && ( (this.getCitaCitaCita()==castOther.getCitaCitaCita()) || ( this.getCitaCitaCita()!=null && castOther.getCitaCitaCita()!=null && this.getCitaCitaCita().equals(castOther.getCitaCitaCita()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFacFactura() == null ? 0 : this.getFacFactura().hashCode() );
         result = 37 * result + ( getCitaCitaCita() == null ? 0 : this.getCitaCitaCita().hashCode() );
         return result;
   }   


}


