package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nomina generated by hbm2java
 */
public class Nomina  implements java.io.Serializable {


     private BigDecimal nomNomina;
     private Date nomFecha;
     private String nomEstado;
     private Set nominaDetalles = new HashSet(0);

    public Nomina() {
    }

	
    public Nomina(BigDecimal nomNomina) {
        this.nomNomina = nomNomina;
    }
    public Nomina(BigDecimal nomNomina, Date nomFecha, String nomEstado, Set nominaDetalles) {
       this.nomNomina = nomNomina;
       this.nomFecha = nomFecha;
       this.nomEstado = nomEstado;
       this.nominaDetalles = nominaDetalles;
    }
   
    public BigDecimal getNomNomina() {
        return this.nomNomina;
    }
    
    public void setNomNomina(BigDecimal nomNomina) {
        this.nomNomina = nomNomina;
    }
    public Date getNomFecha() {
        return this.nomFecha;
    }
    
    public void setNomFecha(Date nomFecha) {
        this.nomFecha = nomFecha;
    }
    public String getNomEstado() {
        return this.nomEstado;
    }
    
    public void setNomEstado(String nomEstado) {
        this.nomEstado = nomEstado;
    }
    public Set getNominaDetalles() {
        return this.nominaDetalles;
    }
    
    public void setNominaDetalles(Set nominaDetalles) {
        this.nominaDetalles = nominaDetalles;
    }




}


