package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * NominaDetalle generated by hbm2java
 */
public class NominaDetalle  implements java.io.Serializable {


     private BigDecimal nomdNominad;
     private Empleado empleado;
     private Nomina nomina;
     private BigDecimal nomdNomina;
     private BigDecimal nomdEmpleado;
     private BigDecimal nomdDiasLabo;
     private BigDecimal nomdHorasx;
     private BigDecimal nomdSalario;
     private BigDecimal nomdNominad2;
     private BigDecimal puePuesto;

    public NominaDetalle() {
    }

	
    public NominaDetalle(BigDecimal nomdNominad, Empleado empleado, Nomina nomina, BigDecimal nomdNominad2, BigDecimal puePuesto) {
        this.nomdNominad = nomdNominad;
        this.empleado = empleado;
        this.nomina = nomina;
        this.nomdNominad2 = nomdNominad2;
        this.puePuesto = puePuesto;
    }
    public NominaDetalle(BigDecimal nomdNominad, Empleado empleado, Nomina nomina, BigDecimal nomdNomina, BigDecimal nomdEmpleado, BigDecimal nomdDiasLabo, BigDecimal nomdHorasx, BigDecimal nomdSalario, BigDecimal nomdNominad2, BigDecimal puePuesto) {
       this.nomdNominad = nomdNominad;
       this.empleado = empleado;
       this.nomina = nomina;
       this.nomdNomina = nomdNomina;
       this.nomdEmpleado = nomdEmpleado;
       this.nomdDiasLabo = nomdDiasLabo;
       this.nomdHorasx = nomdHorasx;
       this.nomdSalario = nomdSalario;
       this.nomdNominad2 = nomdNominad2;
       this.puePuesto = puePuesto;
    }
   
    public BigDecimal getNomdNominad() {
        return this.nomdNominad;
    }
    
    public void setNomdNominad(BigDecimal nomdNominad) {
        this.nomdNominad = nomdNominad;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Nomina getNomina() {
        return this.nomina;
    }
    
    public void setNomina(Nomina nomina) {
        this.nomina = nomina;
    }
    public BigDecimal getNomdNomina() {
        return this.nomdNomina;
    }
    
    public void setNomdNomina(BigDecimal nomdNomina) {
        this.nomdNomina = nomdNomina;
    }
    public BigDecimal getNomdEmpleado() {
        return this.nomdEmpleado;
    }
    
    public void setNomdEmpleado(BigDecimal nomdEmpleado) {
        this.nomdEmpleado = nomdEmpleado;
    }
    public BigDecimal getNomdDiasLabo() {
        return this.nomdDiasLabo;
    }
    
    public void setNomdDiasLabo(BigDecimal nomdDiasLabo) {
        this.nomdDiasLabo = nomdDiasLabo;
    }
    public BigDecimal getNomdHorasx() {
        return this.nomdHorasx;
    }
    
    public void setNomdHorasx(BigDecimal nomdHorasx) {
        this.nomdHorasx = nomdHorasx;
    }
    public BigDecimal getNomdSalario() {
        return this.nomdSalario;
    }
    
    public void setNomdSalario(BigDecimal nomdSalario) {
        this.nomdSalario = nomdSalario;
    }
    public BigDecimal getNomdNominad2() {
        return this.nomdNominad2;
    }
    
    public void setNomdNominad2(BigDecimal nomdNominad2) {
        this.nomdNominad2 = nomdNominad2;
    }
    public BigDecimal getPuePuesto() {
        return this.puePuesto;
    }
    
    public void setPuePuesto(BigDecimal puePuesto) {
        this.puePuesto = puePuesto;
    }




}


