package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private BigDecimal pacPaciente;
     private BigDecimal pacNoCarnet;
     private String pacPersona;
     private String pacEstado;
     private Set personas = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(BigDecimal pacPaciente) {
        this.pacPaciente = pacPaciente;
    }
    public Paciente(BigDecimal pacPaciente, BigDecimal pacNoCarnet, String pacPersona, String pacEstado, Set personas) {
       this.pacPaciente = pacPaciente;
       this.pacNoCarnet = pacNoCarnet;
       this.pacPersona = pacPersona;
       this.pacEstado = pacEstado;
       this.personas = personas;
    }
   
    public BigDecimal getPacPaciente() {
        return this.pacPaciente;
    }
    
    public void setPacPaciente(BigDecimal pacPaciente) {
        this.pacPaciente = pacPaciente;
    }
    public BigDecimal getPacNoCarnet() {
        return this.pacNoCarnet;
    }
    
    public void setPacNoCarnet(BigDecimal pacNoCarnet) {
        this.pacNoCarnet = pacNoCarnet;
    }
    public String getPacPersona() {
        return this.pacPersona;
    }
    
    public void setPacPersona(String pacPersona) {
        this.pacPersona = pacPersona;
    }
    public String getPacEstado() {
        return this.pacEstado;
    }
    
    public void setPacEstado(String pacEstado) {
        this.pacEstado = pacEstado;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


