package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PedidoDetalle generated by hbm2java
 */
public class PedidoDetalle  implements java.io.Serializable {


     private PedidoDetalleId id;
     private Pedido pedido;
     private Producto producto;
     private BigDecimal peddProducto;
     private BigDecimal peddCantidad;
     private BigDecimal peddValor;

    public PedidoDetalle() {
    }

	
    public PedidoDetalle(PedidoDetalleId id, Pedido pedido, Producto producto) {
        this.id = id;
        this.pedido = pedido;
        this.producto = producto;
    }
    public PedidoDetalle(PedidoDetalleId id, Pedido pedido, Producto producto, BigDecimal peddProducto, BigDecimal peddCantidad, BigDecimal peddValor) {
       this.id = id;
       this.pedido = pedido;
       this.producto = producto;
       this.peddProducto = peddProducto;
       this.peddCantidad = peddCantidad;
       this.peddValor = peddValor;
    }
   
    public PedidoDetalleId getId() {
        return this.id;
    }
    
    public void setId(PedidoDetalleId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getPeddProducto() {
        return this.peddProducto;
    }
    
    public void setPeddProducto(BigDecimal peddProducto) {
        this.peddProducto = peddProducto;
    }
    public BigDecimal getPeddCantidad() {
        return this.peddCantidad;
    }
    
    public void setPeddCantidad(BigDecimal peddCantidad) {
        this.peddCantidad = peddCantidad;
    }
    public BigDecimal getPeddValor() {
        return this.peddValor;
    }
    
    public void setPeddValor(BigDecimal peddValor) {
        this.peddValor = peddValor;
    }




}


