package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private BigDecimal pedPedido;
     private BigDecimal pedProveedor;
     private String pedEstado;
     private Date pedFecha;
     private BigDecimal pedValor;
     private Set pedidoDetalles = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(BigDecimal pedPedido) {
        this.pedPedido = pedPedido;
    }
    public Pedido(BigDecimal pedPedido, BigDecimal pedProveedor, String pedEstado, Date pedFecha, BigDecimal pedValor, Set pedidoDetalles) {
       this.pedPedido = pedPedido;
       this.pedProveedor = pedProveedor;
       this.pedEstado = pedEstado;
       this.pedFecha = pedFecha;
       this.pedValor = pedValor;
       this.pedidoDetalles = pedidoDetalles;
    }
   
    public BigDecimal getPedPedido() {
        return this.pedPedido;
    }
    
    public void setPedPedido(BigDecimal pedPedido) {
        this.pedPedido = pedPedido;
    }
    public BigDecimal getPedProveedor() {
        return this.pedProveedor;
    }
    
    public void setPedProveedor(BigDecimal pedProveedor) {
        this.pedProveedor = pedProveedor;
    }
    public String getPedEstado() {
        return this.pedEstado;
    }
    
    public void setPedEstado(String pedEstado) {
        this.pedEstado = pedEstado;
    }
    public Date getPedFecha() {
        return this.pedFecha;
    }
    
    public void setPedFecha(Date pedFecha) {
        this.pedFecha = pedFecha;
    }
    public BigDecimal getPedValor() {
        return this.pedValor;
    }
    
    public void setPedValor(BigDecimal pedValor) {
        this.pedValor = pedValor;
    }
    public Set getPedidoDetalles() {
        return this.pedidoDetalles;
    }
    
    public void setPedidoDetalles(Set pedidoDetalles) {
        this.pedidoDetalles = pedidoDetalles;
    }




}


