package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PedidoDetalleId generated by hbm2java
 */
public class PedidoDetalleId  implements java.io.Serializable {


     private BigDecimal peddPedde;
     private BigDecimal productoProProducto;
     private BigDecimal pedidoPedPedido;

    public PedidoDetalleId() {
    }

    public PedidoDetalleId(BigDecimal peddPedde, BigDecimal productoProProducto, BigDecimal pedidoPedPedido) {
       this.peddPedde = peddPedde;
       this.productoProProducto = productoProProducto;
       this.pedidoPedPedido = pedidoPedPedido;
    }
   
    public BigDecimal getPeddPedde() {
        return this.peddPedde;
    }
    
    public void setPeddPedde(BigDecimal peddPedde) {
        this.peddPedde = peddPedde;
    }
    public BigDecimal getProductoProProducto() {
        return this.productoProProducto;
    }
    
    public void setProductoProProducto(BigDecimal productoProProducto) {
        this.productoProProducto = productoProProducto;
    }
    public BigDecimal getPedidoPedPedido() {
        return this.pedidoPedPedido;
    }
    
    public void setPedidoPedPedido(BigDecimal pedidoPedPedido) {
        this.pedidoPedPedido = pedidoPedPedido;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidoDetalleId) ) return false;
		 PedidoDetalleId castOther = ( PedidoDetalleId ) other; 
         
		 return ( (this.getPeddPedde()==castOther.getPeddPedde()) || ( this.getPeddPedde()!=null && castOther.getPeddPedde()!=null && this.getPeddPedde().equals(castOther.getPeddPedde()) ) )
 && ( (this.getProductoProProducto()==castOther.getProductoProProducto()) || ( this.getProductoProProducto()!=null && castOther.getProductoProProducto()!=null && this.getProductoProProducto().equals(castOther.getProductoProProducto()) ) )
 && ( (this.getPedidoPedPedido()==castOther.getPedidoPedPedido()) || ( this.getPedidoPedPedido()!=null && castOther.getPedidoPedPedido()!=null && this.getPedidoPedPedido().equals(castOther.getPedidoPedPedido()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPeddPedde() == null ? 0 : this.getPeddPedde().hashCode() );
         result = 37 * result + ( getProductoProProducto() == null ? 0 : this.getProductoProProducto().hashCode() );
         result = 37 * result + ( getPedidoPedPedido() == null ? 0 : this.getPedidoPedPedido().hashCode() );
         return result;
   }   


}


