package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PersonaId generated by hbm2java
 */
public class PersonaId  implements java.io.Serializable {


     private BigDecimal perPersona;
     private BigDecimal pacientePacPaciente;

    public PersonaId() {
    }

    public PersonaId(BigDecimal perPersona, BigDecimal pacientePacPaciente) {
       this.perPersona = perPersona;
       this.pacientePacPaciente = pacientePacPaciente;
    }
   
    public BigDecimal getPerPersona() {
        return this.perPersona;
    }
    
    public void setPerPersona(BigDecimal perPersona) {
        this.perPersona = perPersona;
    }
    public BigDecimal getPacientePacPaciente() {
        return this.pacientePacPaciente;
    }
    
    public void setPacientePacPaciente(BigDecimal pacientePacPaciente) {
        this.pacientePacPaciente = pacientePacPaciente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonaId) ) return false;
		 PersonaId castOther = ( PersonaId ) other; 
         
		 return ( (this.getPerPersona()==castOther.getPerPersona()) || ( this.getPerPersona()!=null && castOther.getPerPersona()!=null && this.getPerPersona().equals(castOther.getPerPersona()) ) )
 && ( (this.getPacientePacPaciente()==castOther.getPacientePacPaciente()) || ( this.getPacientePacPaciente()!=null && castOther.getPacientePacPaciente()!=null && this.getPacientePacPaciente().equals(castOther.getPacientePacPaciente()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPerPersona() == null ? 0 : this.getPerPersona().hashCode() );
         result = 37 * result + ( getPacientePacPaciente() == null ? 0 : this.getPacientePacPaciente().hashCode() );
         return result;
   }   


}


