package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private BigDecimal proProducto;
     private String proNombre;
     private String proDescripcio;
     private BigDecimal proPrecio;
     private BigDecimal proCosto;
     private String proTipo;
     private Set facturaDetalles = new HashSet(0);
     private Set productoProveedors = new HashSet(0);
     private Set pedidoDetalles = new HashSet(0);

    public Producto() {
    }

	
    public Producto(BigDecimal proProducto) {
        this.proProducto = proProducto;
    }
    public Producto(BigDecimal proProducto, String proNombre, String proDescripcio, BigDecimal proPrecio, BigDecimal proCosto, String proTipo, Set facturaDetalles, Set productoProveedors, Set pedidoDetalles) {
       this.proProducto = proProducto;
       this.proNombre = proNombre;
       this.proDescripcio = proDescripcio;
       this.proPrecio = proPrecio;
       this.proCosto = proCosto;
       this.proTipo = proTipo;
       this.facturaDetalles = facturaDetalles;
       this.productoProveedors = productoProveedors;
       this.pedidoDetalles = pedidoDetalles;
    }
   
    public BigDecimal getProProducto() {
        return this.proProducto;
    }
    
    public void setProProducto(BigDecimal proProducto) {
        this.proProducto = proProducto;
    }
    public String getProNombre() {
        return this.proNombre;
    }
    
    public void setProNombre(String proNombre) {
        this.proNombre = proNombre;
    }
    public String getProDescripcio() {
        return this.proDescripcio;
    }
    
    public void setProDescripcio(String proDescripcio) {
        this.proDescripcio = proDescripcio;
    }
    public BigDecimal getProPrecio() {
        return this.proPrecio;
    }
    
    public void setProPrecio(BigDecimal proPrecio) {
        this.proPrecio = proPrecio;
    }
    public BigDecimal getProCosto() {
        return this.proCosto;
    }
    
    public void setProCosto(BigDecimal proCosto) {
        this.proCosto = proCosto;
    }
    public String getProTipo() {
        return this.proTipo;
    }
    
    public void setProTipo(String proTipo) {
        this.proTipo = proTipo;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set getProductoProveedors() {
        return this.productoProveedors;
    }
    
    public void setProductoProveedors(Set productoProveedors) {
        this.productoProveedors = productoProveedors;
    }
    public Set getPedidoDetalles() {
        return this.pedidoDetalles;
    }
    
    public void setPedidoDetalles(Set pedidoDetalles) {
        this.pedidoDetalles = pedidoDetalles;
    }




}


