package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ProductoProveedorId generated by hbm2java
 */
public class ProductoProveedorId  implements java.io.Serializable {


     private BigDecimal propProprov;
     private BigDecimal productoProProducto;

    public ProductoProveedorId() {
    }

    public ProductoProveedorId(BigDecimal propProprov, BigDecimal productoProProducto) {
       this.propProprov = propProprov;
       this.productoProProducto = productoProProducto;
    }
   
    public BigDecimal getPropProprov() {
        return this.propProprov;
    }
    
    public void setPropProprov(BigDecimal propProprov) {
        this.propProprov = propProprov;
    }
    public BigDecimal getProductoProProducto() {
        return this.productoProProducto;
    }
    
    public void setProductoProProducto(BigDecimal productoProProducto) {
        this.productoProProducto = productoProProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoProveedorId) ) return false;
		 ProductoProveedorId castOther = ( ProductoProveedorId ) other; 
         
		 return ( (this.getPropProprov()==castOther.getPropProprov()) || ( this.getPropProprov()!=null && castOther.getPropProprov()!=null && this.getPropProprov().equals(castOther.getPropProprov()) ) )
 && ( (this.getProductoProProducto()==castOther.getProductoProProducto()) || ( this.getProductoProProducto()!=null && castOther.getProductoProProducto()!=null && this.getProductoProProducto().equals(castOther.getProductoProProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPropProprov() == null ? 0 : this.getPropProprov().hashCode() );
         result = 37 * result + ( getProductoProProducto() == null ? 0 : this.getProductoProProducto().hashCode() );
         return result;
   }   


}


