package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private ProveedorId id;
     private ProductoProveedor productoProveedor;
     private String provNombre;
     private String provDescripcion;
     private BigDecimal provTelefono;
     private String provDireccion;
     private String provEmpresa;
     private String provCorreo;
     private String provNit;

    public Proveedor() {
    }

	
    public Proveedor(ProveedorId id, ProductoProveedor productoProveedor) {
        this.id = id;
        this.productoProveedor = productoProveedor;
    }
    public Proveedor(ProveedorId id, ProductoProveedor productoProveedor, String provNombre, String provDescripcion, BigDecimal provTelefono, String provDireccion, String provEmpresa, String provCorreo, String provNit) {
       this.id = id;
       this.productoProveedor = productoProveedor;
       this.provNombre = provNombre;
       this.provDescripcion = provDescripcion;
       this.provTelefono = provTelefono;
       this.provDireccion = provDireccion;
       this.provEmpresa = provEmpresa;
       this.provCorreo = provCorreo;
       this.provNit = provNit;
    }
   
    public ProveedorId getId() {
        return this.id;
    }
    
    public void setId(ProveedorId id) {
        this.id = id;
    }
    public ProductoProveedor getProductoProveedor() {
        return this.productoProveedor;
    }
    
    public void setProductoProveedor(ProductoProveedor productoProveedor) {
        this.productoProveedor = productoProveedor;
    }
    public String getProvNombre() {
        return this.provNombre;
    }
    
    public void setProvNombre(String provNombre) {
        this.provNombre = provNombre;
    }
    public String getProvDescripcion() {
        return this.provDescripcion;
    }
    
    public void setProvDescripcion(String provDescripcion) {
        this.provDescripcion = provDescripcion;
    }
    public BigDecimal getProvTelefono() {
        return this.provTelefono;
    }
    
    public void setProvTelefono(BigDecimal provTelefono) {
        this.provTelefono = provTelefono;
    }
    public String getProvDireccion() {
        return this.provDireccion;
    }
    
    public void setProvDireccion(String provDireccion) {
        this.provDireccion = provDireccion;
    }
    public String getProvEmpresa() {
        return this.provEmpresa;
    }
    
    public void setProvEmpresa(String provEmpresa) {
        this.provEmpresa = provEmpresa;
    }
    public String getProvCorreo() {
        return this.provCorreo;
    }
    
    public void setProvCorreo(String provCorreo) {
        this.provCorreo = provCorreo;
    }
    public String getProvNit() {
        return this.provNit;
    }
    
    public void setProvNit(String provNit) {
        this.provNit = provNit;
    }




}


