package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ProveedorId generated by hbm2java
 */
public class ProveedorId  implements java.io.Serializable {


     private BigDecimal provProveedor;
     private BigDecimal productoProveedorPropProprov;
     private BigDecimal productoProveedorProductoProProducto;

    public ProveedorId() {
    }

    public ProveedorId(BigDecimal provProveedor, BigDecimal productoProveedorPropProprov, BigDecimal productoProveedorProductoProProducto) {
       this.provProveedor = provProveedor;
       this.productoProveedorPropProprov = productoProveedorPropProprov;
       this.productoProveedorProductoProProducto = productoProveedorProductoProProducto;
    }
   
    public BigDecimal getProvProveedor() {
        return this.provProveedor;
    }
    
    public void setProvProveedor(BigDecimal provProveedor) {
        this.provProveedor = provProveedor;
    }
    public BigDecimal getProductoProveedorPropProprov() {
        return this.productoProveedorPropProprov;
    }
    
    public void setProductoProveedorPropProprov(BigDecimal productoProveedorPropProprov) {
        this.productoProveedorPropProprov = productoProveedorPropProprov;
    }
    public BigDecimal getProductoProveedorProductoProProducto() {
        return this.productoProveedorProductoProProducto;
    }
    
    public void setProductoProveedorProductoProProducto(BigDecimal productoProveedorProductoProProducto) {
        this.productoProveedorProductoProProducto = productoProveedorProductoProProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProveedorId) ) return false;
		 ProveedorId castOther = ( ProveedorId ) other; 
         
		 return ( (this.getProvProveedor()==castOther.getProvProveedor()) || ( this.getProvProveedor()!=null && castOther.getProvProveedor()!=null && this.getProvProveedor().equals(castOther.getProvProveedor()) ) )
 && ( (this.getProductoProveedorPropProprov()==castOther.getProductoProveedorPropProprov()) || ( this.getProductoProveedorPropProprov()!=null && castOther.getProductoProveedorPropProprov()!=null && this.getProductoProveedorPropProprov().equals(castOther.getProductoProveedorPropProprov()) ) )
 && ( (this.getProductoProveedorProductoProProducto()==castOther.getProductoProveedorProductoProProducto()) || ( this.getProductoProveedorProductoProProducto()!=null && castOther.getProductoProveedorProductoProProducto()!=null && this.getProductoProveedorProductoProProducto().equals(castOther.getProductoProveedorProductoProProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProvProveedor() == null ? 0 : this.getProvProveedor().hashCode() );
         result = 37 * result + ( getProductoProveedorPropProprov() == null ? 0 : this.getProductoProveedorPropProprov().hashCode() );
         result = 37 * result + ( getProductoProveedorProductoProProducto() == null ? 0 : this.getProductoProveedorProductoProProducto().hashCode() );
         return result;
   }   


}


