package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private BigDecimal puePuesto;
     private Departamento departamento;
     private Empleado empleado;
     private String pueDepartam;
     private String pueNombre;
     private String pueDescipcion;
     private BigDecimal puePuesto1;
     private BigDecimal puePuesto2;

    public Puesto() {
    }

	
    public Puesto(BigDecimal puePuesto, Departamento departamento, Empleado empleado, BigDecimal puePuesto1, BigDecimal puePuesto2) {
        this.puePuesto = puePuesto;
        this.departamento = departamento;
        this.empleado = empleado;
        this.puePuesto1 = puePuesto1;
        this.puePuesto2 = puePuesto2;
    }
    public Puesto(BigDecimal puePuesto, Departamento departamento, Empleado empleado, String pueDepartam, String pueNombre, String pueDescipcion, BigDecimal puePuesto1, BigDecimal puePuesto2) {
       this.puePuesto = puePuesto;
       this.departamento = departamento;
       this.empleado = empleado;
       this.pueDepartam = pueDepartam;
       this.pueNombre = pueNombre;
       this.pueDescipcion = pueDescipcion;
       this.puePuesto1 = puePuesto1;
       this.puePuesto2 = puePuesto2;
    }
   
    public BigDecimal getPuePuesto() {
        return this.puePuesto;
    }
    
    public void setPuePuesto(BigDecimal puePuesto) {
        this.puePuesto = puePuesto;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getPueDepartam() {
        return this.pueDepartam;
    }
    
    public void setPueDepartam(String pueDepartam) {
        this.pueDepartam = pueDepartam;
    }
    public String getPueNombre() {
        return this.pueNombre;
    }
    
    public void setPueNombre(String pueNombre) {
        this.pueNombre = pueNombre;
    }
    public String getPueDescipcion() {
        return this.pueDescipcion;
    }
    
    public void setPueDescipcion(String pueDescipcion) {
        this.pueDescipcion = pueDescipcion;
    }
    public BigDecimal getPuePuesto1() {
        return this.puePuesto1;
    }
    
    public void setPuePuesto1(BigDecimal puePuesto1) {
        this.puePuesto1 = puePuesto1;
    }
    public BigDecimal getPuePuesto2() {
        return this.puePuesto2;
    }
    
    public void setPuePuesto2(BigDecimal puePuesto2) {
        this.puePuesto2 = puePuesto2;
    }




}


