package umg.orm;
// Generated 11/03/2020 11:12:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TratamientoId generated by hbm2java
 */
public class TratamientoId  implements java.io.Serializable {


     private BigDecimal traTratamiento;
     private BigDecimal citaCitaCita;

    public TratamientoId() {
    }

    public TratamientoId(BigDecimal traTratamiento, BigDecimal citaCitaCita) {
       this.traTratamiento = traTratamiento;
       this.citaCitaCita = citaCitaCita;
    }
   
    public BigDecimal getTraTratamiento() {
        return this.traTratamiento;
    }
    
    public void setTraTratamiento(BigDecimal traTratamiento) {
        this.traTratamiento = traTratamiento;
    }
    public BigDecimal getCitaCitaCita() {
        return this.citaCitaCita;
    }
    
    public void setCitaCitaCita(BigDecimal citaCitaCita) {
        this.citaCitaCita = citaCitaCita;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TratamientoId) ) return false;
		 TratamientoId castOther = ( TratamientoId ) other; 
         
		 return ( (this.getTraTratamiento()==castOther.getTraTratamiento()) || ( this.getTraTratamiento()!=null && castOther.getTraTratamiento()!=null && this.getTraTratamiento().equals(castOther.getTraTratamiento()) ) )
 && ( (this.getCitaCitaCita()==castOther.getCitaCitaCita()) || ( this.getCitaCitaCita()!=null && castOther.getCitaCitaCita()!=null && this.getCitaCitaCita().equals(castOther.getCitaCitaCita()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTraTratamiento() == null ? 0 : this.getTraTratamiento().hashCode() );
         result = 37 * result + ( getCitaCitaCita() == null ? 0 : this.getCitaCitaCita().hashCode() );
         return result;
   }   


}


